baseURL = "https://tgmerge.me"
title = "tgmerge's blog"
copyright = "CC BY-NC-SA 4.0 / tgmerge"

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 7

preserveTaxonomyNames = true

hasCJKLanguage = true

[params]
  description = "写写代码 吸吸猫"
  dateFormat = "2006-01-02"
  copyrightOwner = "tgmerge"
  copyrightStartYear = "2013"
  favicon = "favicon.png"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "tgmerge"

[author.social]
  #codepen = "MunifTanjim"
  #facebook = "MunifTanjim"
  email = "tgmgsp@gmail.com"
  github = "tgmerge"
  #instagram = "instagram"
  twitter = "tgmerge"
  weibo = "tgmerge"
  googleplus = "tgmergeSipan"
  #linkedin = "muniftanjim"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  #name = "关于"
  #weight = -40
  #identifier = "about"
  #url = "/about/"

# Language Configuration
defaultContentLanguage = "zh-cn"

[languages]
  # edit this block for your own language
  [languages.zh-cn]
    lang = "zh-cn"
    languageName = "Simplified Chinese"
    weight = 0


